export type BusinessArea = "ISO" | "K_BEAUTY";
export type AccreditationTrack = "ACCREDITED" | "NON_ACCREDITED";
export type ApplicationStatus = "INTAKE_REVIEW" | "DOCUMENT_REVIEW" | "SUPPLEMENT_PENDING" | "INVOICE_PENDING" | "PAYMENT_PENDING" | "DECISION_PENDING" | "PARTIALLY_COMPLETED" | "COMPLETED" | "CANCELLED";
export type ProcessingStatus = "DOCUMENT_REVIEW" | "INVOICE_PENDING" | "PAYMENT_PENDING" | "DECISION_PENDING" | "SUPPLEMENT_PENDING" | "CERTIFICATE_DRAFT_PENDING" | "CERTIFICATION_INFO_PENDING" | "DELIVERY_PENDING" | "COMPLETED" | "APPLICATION_CANCELLED";
export type ApplicationType = "최초" | "갱신" | "등급변경" | "기타";
export type CertificationState = "ACTIVE" | "SUSPENDED" | "WITHDRAWN" | "NONE";
export type CertificateHistoryState = "CURRENT" | "REPLACED_BY_RENEWAL" | "REPLACED_BY_GRADE_CHANGE" | "EXPIRED" | "SUSPENDED" | "WITHDRAWN";

export interface Candidate { id: string; name: string; nameEn: string; birthDate: string; nationality: string; phone: string; email: string; address: string; jobIds: string[]; }
export interface CertificationApplication { id: string; applicationNo: string; candidateId: string; businessArea: BusinessArea; accreditationTrack: AccreditationTrack; accreditationHidden?: boolean; applicationType: ApplicationType; receivedAt: string; registeredAt: string; partnerCompany: string; status: ApplicationStatus; managementNoFrom: number; managementNoTo: number; jobIds: string[]; primaryOwner: string; dropboxFolderName: string; dropboxPath?: string; documentsStored: boolean; packageStatus: "NOT_READY" | "READY" | "GENERATED"; invoiceIds: string[]; }
export interface Job { id: string; jobNo: string; managementNo?: number; applicationId?: string; candidateId: string; businessArea?: BusinessArea; accreditationTrack?: AccreditationTrack; partnerCompany: string; standard: string; currentGrade: string; certificationState: CertificationState; primaryOwner: string; cycleIds: string[]; currentCycleId?: string; certificationNo?: string; certificationIssueDate?: string; certificationExpiryDate?: string; certificateRevision?: number; certificateFileName?: string; trackingNumber?: string; }
export interface Invoice { id: string; invoiceNo: string; recipientType: "INDIVIDUAL" | "PARTNER"; recipientName: string; copiedTo: string[]; jobIds: string[]; amount: number; issuedAt: string; paymentStatus: "UNPAID" | "PAID" | "CHECK_REQUIRED"; paidAt?: string; payerName?: string; }
export interface PackageDocument { id: string; jobId: string; type: "DOCUMENT_REVIEW" | "CERTIFICATION_DECISION_REPORT" | "DELIVERY_CONFIRMATION" | "CERTIFICATE"; title: string; formats: Array<"WORD" | "PDF">; status: "READY" | "GENERATED"; templateVersion: string; }
export interface ProcessingCycle { id: string; jobId: string; sequence: number; applicationType: ApplicationType; applicationDate: string; status: ProcessingStatus; plannedIssueDate: string; documentReviewDate: string; decisionDate: string; deliveryDate: string; invoiceNo?: string; invoiceAmount?: number; invoiceIssuedAt?: string; paymentConfirmedAt?: string; certificateDraftStatus?: "미작성" | "작성중" | "확인완료"; completedAt?: string; appliedRule: string; }
export interface DocumentReview { cycleId: string; round: number; documents: Record<string, boolean>; requirements: Record<string, "충족" | "미충족" | "해당없음">; overallResult: "적합" | "보완필요" | "부적합"; comment: string; reviewer: string; reviewedAt: string; }
export interface CertificationDecision { cycleId: string; round: number; result: "승인" | "보완" | "불승인"; comment: string; reviewerId: string; reviewerName: string; enteredBy: string; decidedAt: string; }
export interface CertificationRecord { id: string; jobId: string; cycleId: string; certificationNo: string; issueDate: string; validFrom: string; validUntil: string; state: CertificationState; }
export interface DocumentDelivery { cycleId: string; certificateDelivered: boolean; noticeDelivered: boolean; otherDelivered: boolean; method: "이메일" | "우편" | "직접전달" | "기타"; deliveredAt: string; deliveredBy: string; status: string; note: string; }
export interface AuditLog { id: string; jobId: string; cycleId?: string; occurredAt: string; actor: string; action: string; detail?: string; }
export type CertificationStatus = ProcessingStatus;
export interface CertificationCase { id: string; candidateName: string; registrationNo: string; applicationType: ApplicationType; standard: string; grade: string; applicationDate: string; status: ProcessingStatus; }
