import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, ClipboardList, CreditCard, PackageCheck, ShieldAlert, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ApplicationStatusBadge } from "@/components/application-status-badge";
import { getCandidate, jobs } from "@/data/mock-data";
import { accreditationLabels, applications, businessAreaLabels, invoices } from "@/data/workflow-data";

export default function DashboardPage() {
  const cards = [
    { label: "진행 중 신청", value: applications.filter((item) => !["COMPLETED", "CANCELLED"].includes(item.status)).length, icon: ClipboardList, href: "/applications" },
    { label: "전체 Job", value: jobs.length, icon: BriefcaseBusiness, href: "/jobs" },
    { label: "보완 대기", value: applications.filter((item) => item.status === "SUPPLEMENT_PENDING").length, icon: ShieldAlert, href: "/applications" },
    { label: "입금 확인 대기", value: invoices.filter((invoice) => invoice.paymentStatus === "UNPAID").length, icon: CreditCard, href: "/applications" },
    { label: "패키지 생성 준비", value: applications.filter((item) => item.packageStatus === "READY").length, icon: PackageCheck, href: "/packages" },
  ];
  return <AppShell title="Dashboard" description="ISO와 K-Beauty 신청 접수부터 Job별 인증 패키지까지의 현재 현황입니다.">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({ label, value, icon: Icon, href }) => <Link href={href} key={label} className="group rounded-lg border bg-white p-5 shadow-sm transition hover:border-blue-200 hover:shadow-md"><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-600">{label}</span><span className="rounded-md bg-slate-100 p-2 text-slate-600 group-hover:bg-blue-50 group-hover:text-blue-800"><Icon className="h-4 w-4"/></span></div><p className="mt-4 text-3xl font-semibold text-slate-950">{value}<span className="ml-1 text-sm font-normal text-slate-500">건</span></p></Link>)}</section>
    <section className="mt-6 grid gap-4 md:grid-cols-2"><Link href="/applications?area=ISO" className="rounded-lg border border-blue-100 bg-blue-50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-blue-700">ISO</p><p className="mt-2 text-lg font-semibold">ISO 경영시스템 심사원</p><p className="mt-1 text-sm text-slate-600">신청 {applications.filter((item) => item.businessArea === "ISO").length}건 · Job {jobs.filter((item) => item.businessArea !== "K_BEAUTY").length}건</p></div><ArrowRight className="h-5 w-5 text-blue-800"/></div></Link><Link href="/applications?area=K_BEAUTY" className="rounded-lg border border-rose-100 bg-rose-50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-rose-700">K-BEAUTY</p><p className="mt-2 text-lg font-semibold">K-Beauty 전문가 자격</p><p className="mt-1 text-sm text-slate-600">신청 {applications.filter((item) => item.businessArea === "K_BEAUTY").length}건 · Job {jobs.filter((item) => item.businessArea === "K_BEAUTY").length}건</p></div><ArrowRight className="h-5 w-5 text-rose-800"/></div></Link></section>
    <section className="mt-6 overflow-hidden rounded-lg border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">최근 신청 및 처리 현황</h2><p className="mt-1 text-sm text-slate-500">후보자별 인정·비인정 신청은 각각 독립적으로 관리됩니다.</p></div><Link href="/applications" className="inline-flex items-center gap-1 text-sm font-medium text-blue-700">전체 보기 <ArrowRight className="h-4 w-4"/></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr>{["신청번호","접수일","후보자","분야 / 체계","관리 No.","포함 Job","상태","담당자"].map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{applications.map((application) => { const candidate = getCandidate(application.candidateId)!; const linkedJobs = jobs.filter((job) => application.jobIds.includes(job.id)); return <tr key={application.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-blue-800"><Link href={`/applications/${application.id}`}>{application.applicationNo}</Link></td><td className="px-5 py-4 text-slate-600">{application.receivedAt}</td><td className="px-5 py-4">{candidate.name}</td><td className="px-5 py-4 text-slate-600">{businessAreaLabels[application.businessArea]}<br/><span className="text-xs text-slate-400">{accreditationLabels[application.accreditationTrack]}</span></td><td className="px-5 py-4">{application.managementNoFrom === application.managementNoTo ? application.managementNoFrom : `${application.managementNoFrom}~${application.managementNoTo}`}</td><td className="px-5 py-4 text-slate-600">{linkedJobs.map((job) => job.standard).join(", ")}</td><td className="px-5 py-4"><ApplicationStatusBadge status={application.status}/></td><td className="px-5 py-4 text-slate-600">{application.primaryOwner}</td></tr>; })}</tbody></table></div></section>
    <section className="mt-6 rounded-lg border bg-slate-900 p-5 text-white"><div className="flex items-center gap-3"><Users className="h-5 w-5 text-blue-300"/><div><p className="font-semibold">공통 후보자, 독립된 신청과 Job</p><p className="mt-1 text-sm text-slate-300">같은 후보자가 여러 발행 체계와 세부 분야를 보유해도 후보자 화면에서 전체 이력을 연결해 볼 수 있습니다.</p></div></div></section>
  </AppShell>;
}
