"use client";

import Link from "next/link";
import { useState } from "react";
import { Check, Copy, Download, ExternalLink, FileArchive, FileText, FolderOpen, PackageCheck, Save } from "lucide-react";
import type { Candidate, CertificationApplication, Invoice, Job } from "@/types/certification";
import { accreditationLabels, businessAreaLabels, packageDocuments } from "@/data/workflow-data";
import { ApplicationStatusBadge } from "@/components/application-status-badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, controlClass, textareaClass } from "@/components/form-fields";

const tabs = ["신청 개요", "자료보관", "서류검토", "인보이스·입금", "인증심의", "Job·패키지"] as const;
type Tab = (typeof tabs)[number];

export function ApplicationDetail({ application, candidate, linkedJobs, invoices }: { application: CertificationApplication; candidate: Candidate; linkedJobs: Job[]; invoices: Invoice[] }) {
  const [active, setActive] = useState<Tab>("신청 개요");
  return <div className="space-y-5">
    <section className="rounded-lg border bg-white p-5 shadow-sm"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-6"><Summary label="후보자" value={candidate.name}/><Summary label="분야" value={businessAreaLabels[application.businessArea]}/><Summary label="인정 구분" value={accreditationLabels[application.accreditationTrack]}/><Summary label="공식 접수일" value={application.receivedAt}/><Summary label="관리 No." value={application.managementNoFrom === application.managementNoTo ? String(application.managementNoFrom) : `${application.managementNoFrom}~${application.managementNoTo}`}/><div><p className="text-xs font-medium text-slate-500">현재상태</p><div className="mt-1.5"><ApplicationStatusBadge status={application.status}/></div></div></div></section>
    <div className="overflow-x-auto rounded-lg border bg-white px-2"><div className="flex min-w-max">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`border-b-2 px-4 py-3 text-sm font-medium ${active === tab ? "border-blue-800 text-blue-800" : "border-transparent text-slate-500 hover:text-slate-800"}`}>{tab}</button>)}</div></div>

    {active === "신청 개요" && <div className="grid gap-5 xl:grid-cols-2"><Section title="접수정보"><dl className="grid gap-5 sm:grid-cols-2"><Info label="신청번호" value={application.applicationNo}/><Info label="신청구분" value={application.applicationType}/><Info label="파트너사" value={application.partnerCompany}/><Info label="주 담당자" value={application.primaryOwner}/><Info label="시스템 등록일시" value={application.registeredAt}/><Info label="등록 Job 수" value={`${linkedJobs.length}건`}/></dl></Section><Section title="Dropbox 신청 폴더" description="자료는 외부 보관하고 시스템에는 폴더명과 경로를 기록합니다."><div className="rounded-md bg-slate-50 p-4"><div className="flex items-start gap-3"><FolderOpen className="mt-0.5 h-5 w-5 text-blue-800"/><div className="min-w-0"><p className="font-semibold">{application.dropboxFolderName}</p><p className="mt-1 break-all text-xs text-slate-500">{application.dropboxPath}</p></div></div></div><div className="mt-4 flex gap-2"><Button variant="outline"><Copy/>폴더명 복사</Button><Button variant="outline"><ExternalLink/>경로 열기</Button></div></Section></div>}

    {active === "자료보관" && <Section title="대표메일 수신 및 Dropbox 보관" description="파일 자체는 Dropbox에 두고 수신·보관 여부만 기록합니다."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["신청서", "계약서", "교육 증빙", "학력 증빙", "업무경력 증빙", "심사·실무경력 증빙"].map((document, index) => <label key={document} className="flex items-center gap-3 rounded-md border p-3 text-sm"><Checkbox defaultChecked={index < 4}/><span>{document}</span><span className={`ml-auto text-xs ${index < 4 ? "text-emerald-700" : "text-orange-700"}`}>{index < 4 ? "보관 완료" : "확인 필요"}</span></label>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="최초 메일 수신일"><input type="date" className={controlClass} value={application.receivedAt} readOnly/></Field><Field label="Dropbox 보관 확인자"><input className={controlClass} defaultValue={application.primaryOwner}/></Field><Field label="누락 및 추가자료 메모" className="sm:col-span-2"><textarea className={textareaClass} defaultValue="심사·실무경력 증빙 추가 확인 필요"/></Field></div><div className="mt-5 flex justify-end"><Button className="bg-blue-800 hover:bg-blue-900"><Save/>보관상태 저장</Button></div></Section>}

    {active === "서류검토" && <div className="space-y-5"><Section title="통합 서류검토" description="신청 전체에 한 번 작성하고 문제가 있는 특정 Job만 보완 대상으로 지정할 수 있습니다."><div className="grid gap-3 sm:grid-cols-2">{["교육요건", "학력요건", "업무경력요건", "심사·실무경력요건"].map((requirement) => <div key={requirement} className="rounded-md border p-4"><p className="text-sm font-semibold">{requirement}</p><div className="mt-3 flex gap-4 text-sm"><label><input type="radio" name={requirement} defaultChecked/> 충족</label><label><input type="radio" name={requirement}/> 미충족</label><label><input type="radio" name={requirement}/> 해당없음</label></div></div>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="종합 검토결과"><select className={controlClass}><option>적합</option><option>보완필요</option><option>부적합</option></select></Field><Field label="검토자"><input className={controlClass} defaultValue={application.primaryOwner}/></Field><Field label="검토의견" className="sm:col-span-2"><textarea className={textareaClass} placeholder="통합 검토의견을 입력합니다."/></Field></div></Section><Section title="보완 적용 대상" description="공통 사유를 작성하고 필요한 경우 Job별 상세 사유를 추가합니다."><div className="space-y-3">{linkedJobs.map((job) => <label key={job.id} className="flex items-center gap-3 rounded-md border p-3"><Checkbox/><span className="text-sm font-semibold">{job.standard} / {job.currentGrade}</span><span className="ml-auto text-xs text-slate-500">{job.jobNo}</span></label>)}</div><Field label="공통 보완 사유" className="mt-4"><textarea className={textareaClass} placeholder="선택한 Job에 공통으로 적용할 사유"/></Field><div className="mt-5 flex justify-end gap-2"><Button variant="outline">임시저장</Button><Button className="bg-blue-800 hover:bg-blue-900"><Check/>서류검토 확정</Button></div></Section></div>}

    {active === "인보이스·입금" && <Section title="인보이스 및 입금" description="서류검토가 완료된 Job을 선택해 하나의 인보이스로 전액 청구합니다.">{invoices.length ? <div className="space-y-3">{invoices.map((invoice) => <div key={invoice.id} className="grid gap-4 rounded-lg border p-4 sm:grid-cols-2 lg:grid-cols-5"><Info label="인보이스 번호" value={invoice.invoiceNo}/><Info label="수신자" value={invoice.recipientName}/><Info label="청구금액" value={`${invoice.amount.toLocaleString("ko-KR")}원`}/><Info label="발행일" value={invoice.issuedAt}/><Info label="입금상태" value={invoice.paymentStatus === "PAID" ? `입금 완료 · ${invoice.paidAt}` : "입금 대기"}/></div>)}</div> : <div className="rounded-lg border border-dashed p-8 text-center text-sm text-slate-500">발행된 인보이스가 없습니다.</div>}<div className="mt-5 flex justify-end"><Button className="bg-blue-800 hover:bg-blue-900"><FileText/>인보이스 발행 기록</Button></div></Section>}

    {active === "인증심의" && <Section title="인증심의 및 인증결정보고서" description="후보자별 신청 단위로 심의하고 Job별 결과를 각각 기록합니다."><div className="mb-5 grid gap-4 sm:grid-cols-3"><Field label="심의자"><select className={controlClass}><option>박심의</option><option>이위원</option></select></Field><Field label="심의일"><input type="date" className={controlClass} defaultValue="2026-09-02"/></Field><Field label="보고서 방식"><select className={controlClass}><option>통합 인증결정보고서</option><option>개별 Job 보고서</option></select></Field></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">대상</th><th className="px-4 py-3">Job No.</th><th className="px-4 py-3">세부 분야 / 등급</th><th className="px-4 py-3">심의결과</th><th className="px-4 py-3">의견</th></tr></thead><tbody className="divide-y">{linkedJobs.map((job) => <tr key={job.id}><td className="px-4 py-3"><Checkbox defaultChecked/></td><td className="px-4 py-3 font-medium text-blue-800">{job.jobNo}</td><td className="px-4 py-3">{job.standard} / {job.currentGrade}</td><td className="px-4 py-3"><select className={controlClass}><option>승인</option><option>보완</option><option>불승인</option></select></td><td className="px-4 py-3"><input className={controlClass} placeholder="Job별 의견"/></td></tr>)}</tbody></table></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline">임시저장</Button><Button className="bg-blue-800 hover:bg-blue-900"><Check/>심의 완료</Button></div></Section>}

    {active === "Job·패키지" && <Section title="Job별 자동 패키지" description="저장·추적은 Job별로 하고 여러 Job을 선택해 일괄 생성할 수 있습니다."><div className="space-y-4">{linkedJobs.map((job) => { const docs = packageDocuments.filter((document) => document.jobId === job.id); return <div key={job.id} className="rounded-lg border"><div className="flex flex-col gap-3 border-b bg-slate-50 p-4 sm:flex-row sm:items-center"><Checkbox/><div className="flex-1"><p className="font-semibold">{job.standard} / {job.currentGrade}</p><p className="mt-1 text-xs text-slate-500">관리 No. {job.managementNo ?? "-"} · {job.jobNo} · 인증번호 {job.certificationNo ?? "미부여"}</p></div><Button variant="outline" asChild><Link href={`/jobs/${job.id}`}>Job 열기</Link></Button></div><div className="p-4">{docs.length ? <div className="grid gap-3 md:grid-cols-2">{docs.map((document) => <div key={document.id} className="flex items-center gap-3 rounded-md border p-3"><FileText className="h-4 w-4 text-slate-500"/><div className="flex-1"><p className="text-sm font-medium">{document.title}</p><p className="text-xs text-slate-400">{document.templateVersion}</p></div><span className="text-xs font-semibold text-emerald-700">{document.status === "GENERATED" ? "생성 완료" : "생성 준비"}</span></div>)}</div> : <p className="text-sm text-slate-500">인증서 발행일 확정 후 패키지를 생성할 수 있습니다.</p>}</div></div>; })}</div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="outline"><Download/>개별 문서</Button><Button variant="outline"><FileArchive/>ZIP 다운로드</Button><Button className="bg-blue-800 hover:bg-blue-900"><PackageCheck/>선택 Job 패키지 일괄 생성</Button></div></Section>}
  </div>;
}

function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-lg border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-semibold">{title}</h3>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div><div className="p-5">{children}</div></section>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1.5 text-sm font-semibold text-slate-900">{value}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1.5 text-sm font-medium text-slate-900">{value}</dd></div>; }
