"use client";
import Link from "next/link";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { certificationCases, statusLabels } from "@/data/mock-data";
import { StatusBadge } from "@/components/status-badge";
import type { CertificationStatus } from "@/types/certification";
export function CasesTable() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<CertificationStatus | "ALL">("ALL");
  const items = useMemo(() => certificationCases.filter((item) => (status === "ALL" || item.status === status) && `${item.candidateName} ${item.registrationNo} ${item.standard}`.toLowerCase().includes(query.toLowerCase())), [query, status]);
  return <section className="overflow-hidden rounded-lg border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-9 w-full rounded-md border bg-white pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-blue-200" placeholder="후보자명, Registration No., 인증규격 검색" /></label><select value={status} onChange={(e) => setStatus(e.target.value as CertificationStatus | "ALL")} className="h-9 rounded-md border bg-white px-3 text-sm text-slate-700 outline-none focus:ring-2 focus:ring-blue-200"><option value="ALL">전체 상태</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr>{["후보자명","Registration No.","신청구분","인증규격","신청등급","신청일","현재상태"].map((head) => <th className="px-5 py-3" key={head}>{head}</th>)}</tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id} className="hover:bg-blue-50/40"><td className="px-5 py-4 font-semibold"><Link className="block hover:text-blue-800" href={`/cases/${item.id}`}>{item.candidateName}</Link></td><td className="px-5 py-4 text-slate-600">{item.registrationNo}</td><td className="px-5 py-4 text-slate-600">{item.applicationType}</td><td className="px-5 py-4 text-slate-600">{item.standard}</td><td className="px-5 py-4 text-slate-600">{item.grade}</td><td className="px-5 py-4 text-slate-600">{item.applicationDate}</td><td className="px-5 py-4"><StatusBadge status={item.status} /></td></tr>)}{items.length === 0 && <tr><td colSpan={7} className="px-5 py-16 text-center text-slate-500">검색 조건에 맞는 인증건이 없습니다.</td></tr>}</tbody></table></div><div className="border-t px-5 py-3 text-xs text-slate-500">총 {items.length}건</div></section>;
}
