"use client";
import { useState } from "react";
import { Check, Circle, Info, Save } from "lucide-react";
import { auditLogs } from "@/data/mock-data";
import type { CertificationCase } from "@/types/certification";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, controlClass, textareaClass } from "@/components/form-fields";

const tabs = ["기본정보", "서류검토", "인증심의", "인증정보", "문서전달", "처리이력"] as const;
type Tab = (typeof tabs)[number];
const requirements = ["교육요건", "학력요건", "업무경력요건", "심사경력요건"];
const documents = ["신청서", "계약서", "교육 증빙", "학력 증빙", "업무경력 증빙", "심사경력 증빙"];

function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-lg border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-semibold text-slate-950">{title}</h3>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div><div className="p-5">{children}</div></section>; }
function Actions({ primary }: { primary: string }) { return <div className="flex justify-end gap-2"><Button variant="outline" type="button"><Save />임시저장</Button><Button type="button" className="bg-blue-800 hover:bg-blue-900"><Check />{primary}</Button></div>; }
function RadioGroup({ name, values, defaultValue }: { name: string; values: string[]; defaultValue?: string }) { return <div className="flex flex-wrap gap-x-5 gap-y-2">{values.map((value) => <label key={value} className="flex items-center gap-2 text-sm text-slate-700"><input type="radio" name={name} value={value} defaultChecked={value === defaultValue} className="h-4 w-4 accent-blue-800" />{value}</label>)}</div>; }

export function CaseDetail({ item }: { item: CertificationCase }) {
  const [active, setActive] = useState<Tab>("기본정보");
  return <div className="space-y-5"><section className="rounded-lg border bg-white p-5 shadow-sm"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><Summary label="후보자명" value={item.candidateName} /><Summary label="Registration No." value={item.registrationNo} /><Summary label="인증규격" value={item.standard} /><Summary label="신청등급" value={item.grade} /><div><p className="mb-2 text-xs font-medium text-slate-500">현재 상태</p><StatusBadge status={item.status} /></div></div></section>
    <div className="overflow-x-auto rounded-lg border bg-white px-2"><div className="flex min-w-max">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`border-b-2 px-4 py-3 text-sm font-medium transition ${active === tab ? "border-blue-800 text-blue-800" : "border-transparent text-slate-500 hover:text-slate-800"}`}>{tab}</button>)}</div></div>
    {active === "기본정보" && <Section title="기본정보" description="인증건 등록 시 입력한 신청 정보입니다."><dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2"><InfoRow label="후보자명" value={item.candidateName} /><InfoRow label="Registration No." value={item.registrationNo} /><InfoRow label="신청구분" value={item.applicationType} /><InfoRow label="인증규격" value={item.standard} /><InfoRow label="신청등급" value={item.grade} /><InfoRow label="신청일" value={item.applicationDate} /></dl></Section>}
    {active === "서류검토" && <div className="space-y-5"><Section title="제출서류 확인" description="제출된 서류를 항목별로 확인합니다."><div className="grid gap-3 sm:grid-cols-2">{documents.map((doc, index) => <label key={doc} className="flex items-center gap-3 rounded-md border p-3 text-sm"><Checkbox defaultChecked={index < 4} />{doc}<span className="ml-auto text-xs text-slate-500">{index < 4 ? "확인" : "미확인"}</span></label>)}</div></Section><Section title="요구사항 검토"><div className="divide-y">{requirements.map((req, index) => <div key={req} className="grid gap-3 py-4 first:pt-0 last:pb-0 sm:grid-cols-[180px_1fr]"><p className="text-sm font-medium">{req}</p><RadioGroup name={req} values={["충족","미충족","해당없음"]} defaultValue={index === 1 ? "해당없음" : "충족"} /></div>)}</div></Section><Section title="종합 검토결과"><div className="space-y-5"><Field label="종합 검토결과"><RadioGroup name="overall" values={["적합","보완필요","부적합"]} defaultValue="적합" /></Field><Field label="검토의견"><textarea className={textareaClass} placeholder="검토 근거와 보완 요청사항을 기록합니다." /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="검토자"><input className={controlClass} defaultValue="김담당" /></Field><Field label="검토일"><input type="date" className={controlClass} defaultValue="2026-08-30" /></Field></div><div className="rounded-md border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900"><Info className="mr-2 inline h-4 w-4" />서류검토 완료 시 상태가 인증심의 대기로 변경되도록 연결할 예정입니다.</div><Actions primary="서류검토 완료" /></div></Section></div>}
    {active === "인증심의" && <div className="space-y-5"><Section title="서류검토 결과 요약"><div className="grid gap-4 sm:grid-cols-3"><Summary label="후보자명" value={item.candidateName} /><Summary label="인증규격 / 신청등급" value={`${item.standard} / ${item.grade}`} /><Summary label="서류검토 결과" value="적합" /><Summary label="검토자" value="김담당" /><Summary label="검토일" value="2026-08-29" /></div></Section><Section title="인증심의 기록" description="심의자가 직접 결과를 선택하고 근거를 기록합니다. AI 추천이나 자동선택은 제공하지 않습니다."><div className="space-y-5"><Field label="심의결과"><RadioGroup name="decision" values={["승인","보완","불승인"]} /></Field><Field label="심의의견"><textarea className={textareaClass} placeholder="심의 근거와 의견을 입력합니다." /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="심의자"><input className={controlClass} placeholder="심의자명" /></Field><Field label="심의일"><input type="date" className={controlClass} defaultValue="2026-08-30" /></Field></div><Actions primary="심의 완료" /></div></Section></div>}
    {active === "인증정보" && <Section title="인증정보" description="확정된 인증정보를 기록합니다. 인증서는 자동 생성되지 않습니다."><div className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="인증번호"><input className={controlClass} placeholder="인증번호 입력" /></Field><Field label="인증일"><input type="date" className={controlClass} /></Field><Field label="유효시작일"><input type="date" className={controlClass} /></Field><Field label="유효종료일"><input type="date" className={controlClass} /></Field></div><Field label="인증서 발행여부"><RadioGroup name="issued" values={["발행","미발행"]} defaultValue="미발행" /></Field><div className="flex justify-end"><Button type="button" className="bg-blue-800 hover:bg-blue-900"><Save />인증정보 저장</Button></div></div></Section>}
    {active === "문서전달" && <Section title="문서전달 기록" description="인증 관련 문서의 전달 내역을 기록합니다."><div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{["인증서 전달 여부","인증 관련 안내문 전달 여부","기타 문서 전달 여부"].map((label) => <label key={label} className="flex items-center gap-3 rounded-md border p-3 text-sm"><Checkbox />{label}</label>)}</div><div className="grid gap-5 sm:grid-cols-2"><Field label="전달방법"><select className={controlClass}><option>이메일</option><option>우편</option><option>직접전달</option><option>기타</option></select></Field><Field label="전달일"><input type="date" className={controlClass} /></Field><Field label="전달담당자"><input className={controlClass} placeholder="담당자명" /></Field><Field label="전달상태"><select className={controlClass}><option>전달 대기</option><option>전달 완료</option><option>재전달 필요</option></select></Field></div><Field label="비고"><textarea className={textareaClass} placeholder="전달 관련 참고사항을 입력합니다." /></Field><div className="flex justify-end"><Button type="button" className="bg-blue-800 hover:bg-blue-900"><Check />문서전달 완료</Button></div></div></Section>}
    {active === "처리이력" && <Section title="처리이력" description="인증건의 주요 처리 기록입니다. 향후 audit_logs 테이블과 연결됩니다."><ol className="relative ml-2 border-l border-slate-200">{auditLogs.map((log) => <li key={log.id} className="relative ml-6 pb-7 last:pb-0"><span className="absolute -left-[31px] top-1 grid h-4 w-4 place-items-center rounded-full bg-blue-800 ring-4 ring-white"><Circle className="h-2 w-2 fill-white text-white" /></span><p className="text-xs text-slate-500">{log.occurredAt}</p><div className="mt-1 flex flex-wrap items-baseline gap-2"><p className="font-semibold text-slate-900">{log.action}</p><span className="text-sm text-slate-500">{log.actor}</span></div>{log.detail && <p className="mt-1 text-sm text-blue-800">{log.detail}</p>}</li>)}</ol></Section>}
  </div>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1.5 text-sm font-semibold text-slate-900">{value}</p></div>; }
function InfoRow({ label, value }: { label: string; value: string }) { return <div className="border-b pb-3"><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1.5 text-sm font-medium text-slate-900">{value}</dd></div>; }
