"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Plus, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Field, controlClass, textareaClass } from "@/components/form-fields";
import { readTrainingInstitutions, saveTrainingInstitutions, type TrainingInstitution } from "@/lib/training-institutions";

const STORAGE_KEY = "certification-general-settings";
type Settings = { reviewers: string; reviewDays: string; decisionDays: string; deliveryDays: string; suspensionReasons: string; withdrawalReasons: string; users: string[] };
const defaults: Settings = { reviewers: "박심의, 이위원, 최위원", reviewDays: "10", decisionDays: "5", deliveryDays: "1", suspensionReasons: "자격유지 요구사항 미충족\n인증서 오용\n시정조치 미이행\n기타", withdrawalReasons: "중대한 인증서 오용\n정지 후 시정조치 미이행\n본인 요청", users: ["김담당", "오실무", "정실무"] };

export function GeneralSettings() {
  const [settings, setSettings] = useState(defaults);
  const [invite, setInvite] = useState("");
  const [notice, setNotice] = useState("");
  const [institutions, setInstitutions] = useState<TrainingInstitution[]>([]);
  const [institutionDraft, setInstitutionDraft] = useState({ id: "", name: "", designationNo: "", validFrom: "", validUntil: "", standards: "" });
  useEffect(() => { try { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) setSettings({ ...defaults, ...JSON.parse(saved) }); } catch {} setInstitutions(readTrainingInstitutions()); }, []);
  const save = () => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(settings)); setNotice("설정이 이 브라우저에 저장되었습니다. 새 회차부터 적용됩니다."); };
  const addUser = () => { if (!invite.trim()) return; setSettings((current) => ({ ...current, users: [...current.users, invite.trim()] })); setInvite(""); setNotice("테스트 사용자가 명단에 추가되었습니다. 실제 초대메일은 전송하지 않습니다."); };
  const saveInstitution = () => { if (!institutionDraft.name.trim() || !institutionDraft.designationNo.trim() || !institutionDraft.validFrom || !institutionDraft.validUntil || !institutionDraft.standards.trim()) { setNotice("연수기관명, 지정번호, 유효기간, 신청표준을 모두 입력해 주세요."); return; } const record: TrainingInstitution = { id: institutionDraft.id || `training-${Date.now()}`, name: institutionDraft.name.trim(), designationNo: institutionDraft.designationNo.trim(), validFrom: institutionDraft.validFrom, validUntil: institutionDraft.validUntil, standards: institutionDraft.standards.split(",").map((item) => item.trim()).filter(Boolean), active: true }; const next = institutionDraft.id ? institutions.map((item) => item.id === institutionDraft.id ? { ...record, active: item.active } : item) : [...institutions, record]; setInstitutions(next); saveTrainingInstitutions(next); setInstitutionDraft({ id: "", name: "", designationNo: "", validFrom: "", validUntil: "", standards: "" }); setNotice(institutionDraft.id ? "협약 연수기관 정보를 수정했습니다." : "협약 연수기관을 등록했습니다."); };
  const editInstitution = (item: TrainingInstitution) => setInstitutionDraft({ id: item.id, name: item.name, designationNo: item.designationNo, validFrom: item.validFrom, validUntil: item.validUntil, standards: item.standards.join(", ") });
  const toggleInstitution = (id: string) => { const next = institutions.map((item) => item.id === id ? { ...item, active: !item.active } : item); setInstitutions(next); saveTrainingInstitutions(next); setNotice("연수기관 사용 상태를 변경했습니다."); };
  return <div className="mt-6 space-y-6">
    {notice && <div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-900"><CheckCircle2 className="h-4 w-4"/>{notice}</div>}
    <section id="reviewers" className="scroll-mt-20 rounded-lg border bg-white shadow-sm"><Header title="심의자 명단" description="인증심의 단계에서 선택할 패널 명단입니다."/><div className="p-5"><Field label="심의자 이름 (쉼표로 구분)"><input className={controlClass} value={settings.reviewers} onChange={(event) => setSettings({ ...settings, reviewers: event.target.value })}/></Field></div></section>
    <section id="date-rules" className="scroll-mt-20 rounded-lg border bg-white shadow-sm"><Header title="업무일자 계산 규칙" description="인증서 발행일 기준 영업일 간격입니다. 변경값은 새 회차부터 적용합니다."/><div className="grid gap-4 p-5 sm:grid-cols-3"><Field label="서류검토일 (발행 전)"><input type="number" className={controlClass} value={settings.reviewDays} onChange={(event) => setSettings({ ...settings, reviewDays: event.target.value })}/></Field><Field label="인증심의일 (발행 전)"><input type="number" className={controlClass} value={settings.decisionDays} onChange={(event) => setSettings({ ...settings, decisionDays: event.target.value })}/></Field><Field label="문서전달일 (발행 후)"><input type="number" className={controlClass} value={settings.deliveryDays} onChange={(event) => setSettings({ ...settings, deliveryDays: event.target.value })}/></Field></div></section>
    <section id="reasons" className="scroll-mt-20 rounded-lg border bg-white shadow-sm"><Header title="정지·철회 표준 사유" description="한 줄에 하나씩 입력하며 향후 보고서 선택 항목으로 사용합니다."/><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="인증 정지 사유"><textarea className={textareaClass} value={settings.suspensionReasons} onChange={(event) => setSettings({ ...settings, suspensionReasons: event.target.value })}/></Field><Field label="인증 철회 사유"><textarea className={textareaClass} value={settings.withdrawalReasons} onChange={(event) => setSettings({ ...settings, withdrawalReasons: event.target.value })}/></Field></div></section>
    <section id="users" className="scroll-mt-20 rounded-lg border bg-white shadow-sm"><Header title="사용자 및 권한" description="현재는 테스트 명단만 관리하며 실제 이메일 초대는 Supabase 연결 후 적용합니다."/><div className="p-5"><div className="mb-4 flex flex-wrap gap-2">{settings.users.map((user) => <span key={user} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-medium text-slate-700">{user} · 실무자</span>)}</div><div className="flex gap-2"><input type="email" className={controlClass} value={invite} onChange={(event) => setInvite(event.target.value)} placeholder="직원 이메일 또는 이름"/><Button type="button" variant="outline" onClick={addUser}><Plus/>명단 추가</Button></div></div></section>
    <section id="training-institutions" className="scroll-mt-20 rounded-lg border bg-white shadow-sm"><Header title="협약 연수기관 관리" description="유효한 협약 연수기관과 교육 가능한 신청표준을 관리합니다."/><div className="p-5"><div className="grid gap-4 rounded-lg border bg-slate-50 p-4 md:grid-cols-2 xl:grid-cols-5"><Field label="연수기관명"><input className={controlClass} value={institutionDraft.name} onChange={(event) => setInstitutionDraft({ ...institutionDraft, name: event.target.value })}/></Field><Field label="지정번호"><input className={controlClass} value={institutionDraft.designationNo} onChange={(event) => setInstitutionDraft({ ...institutionDraft, designationNo: event.target.value })}/></Field><Field label="유효기간 시작"><input type="date" className={controlClass} value={institutionDraft.validFrom} onChange={(event) => setInstitutionDraft({ ...institutionDraft, validFrom: event.target.value })}/></Field><Field label="유효기간 종료"><input type="date" className={controlClass} value={institutionDraft.validUntil} onChange={(event) => setInstitutionDraft({ ...institutionDraft, validUntil: event.target.value })}/></Field><Field label="신청표준"><input className={controlClass} value={institutionDraft.standards} onChange={(event) => setInstitutionDraft({ ...institutionDraft, standards: event.target.value })} placeholder="ISO 9001, ISO 14001"/></Field></div><div className="mt-3 flex justify-end gap-2">{institutionDraft.id && <Button variant="outline" onClick={() => setInstitutionDraft({ id: "", name: "", designationNo: "", validFrom: "", validUntil: "", standards: "" })}>수정 취소</Button>}<Button onClick={saveInstitution}><Plus/>{institutionDraft.id ? "수정 저장" : "연수기관 등록"}</Button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-3 text-left">연수기관명</th><th className="px-3 py-3 text-left">지정번호</th><th className="px-3 py-3 text-left">유효기간</th><th className="px-3 py-3 text-left">신청표준</th><th className="px-3 py-3 text-center">상태</th><th className="px-3 py-3 text-right">관리</th></tr></thead><tbody className="divide-y">{institutions.map((item) => <tr key={item.id}><td className="px-3 py-3 font-medium">{item.name}</td><td className="px-3 py-3">{item.designationNo}</td><td className="whitespace-nowrap px-3 py-3">{item.validFrom} ~ {item.validUntil}</td><td className="px-3 py-3">{item.standards.join(", ")}</td><td className="px-3 py-3 text-center"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.active ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-500"}`}>{item.active ? "사용" : "비활성"}</span></td><td className="whitespace-nowrap px-3 py-3 text-right"><Button size="sm" variant="outline" onClick={() => editInstitution(item)}>수정</Button><Button size="sm" variant="outline" className="ml-2" onClick={() => toggleInstitution(item.id)}>{item.active ? "비활성" : "활성"}</Button></td></tr>)}</tbody></table></div></div></section>
    <div className="flex justify-end"><Button onClick={save} className="bg-blue-800 hover:bg-blue-900"><Save/>전체 설정 저장</Button></div>
  </div>;
}

function Header({ title, description }: { title: string; description: string }) { return <div className="border-b px-5 py-4"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>; }
