"use client";
import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, CalendarDays, Check, Circle, ExternalLink, FileText, LockKeyhole, Save, UserRound } from "lucide-react";
import type { Candidate, Job } from "@/types/certification";
import { auditLogs, certificationStateLabels, getCurrentCycle, processingCycles } from "@/data/mock-data";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, controlClass, textareaClass } from "@/components/form-fields";

const tabs = ["Job 개요", "현재 처리", "회차 이력", "인증정보", "정지·철회", "처리이력"] as const;
type Tab = (typeof tabs)[number];
const documents = ["신청서", "계약서", "교육 증빙", "학력 증빙", "업무경력 증빙", "심사경력 증빙"];

export function JobDetail({job,candidate}:{job:Job;candidate:Candidate}){
  const [active,setActive]=useState<Tab>(job.currentCycleId?"현재 처리":"Job 개요"); const current=getCurrentCycle(job); const cycles=processingCycles.filter((cycle)=>cycle.jobId===job.id).sort((a,b)=>b.sequence-a.sequence);
  const [activeStatus,setActiveStatus]=useState(current?.status); const [notice,setNotice]=useState("");
  return <div className="space-y-5"><section className="rounded-lg border bg-white p-5 shadow-sm"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-6"><Summary label="후보자" value={candidate.name}/><Summary label="인증규격" value={job.standard}/><Summary label="현재등급" value={job.currentGrade}/><Summary label="인증번호" value={job.certificationNo??"미발행"}/><Summary label="주 담당자" value={job.primaryOwner}/><div><p className="text-xs font-medium text-slate-500">인증상태</p><p className={`mt-1.5 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${job.certificationState==="ACTIVE"?"bg-emerald-50 text-emerald-800":job.certificationState==="SUSPENDED"?"bg-orange-50 text-orange-800":"bg-slate-100 text-slate-600"}`}>{certificationStateLabels[job.certificationState]}</p></div></div></section><div className="overflow-x-auto rounded-lg border bg-white px-2"><div className="flex min-w-max">{tabs.map((tab)=><button key={tab} onClick={()=>setActive(tab)} className={`border-b-2 px-4 py-3 text-sm font-medium ${active===tab?"border-blue-800 text-blue-800":"border-transparent text-slate-500 hover:text-slate-800"}`}>{tab}</button>)}</div></div>
    {active==="Job 개요"&&<div className="grid gap-5 xl:grid-cols-2"><Section title="후보자 연결정보"><dl className="grid gap-5 sm:grid-cols-2"><Info label="후보자명" value={candidate.name}/><Info label="영문명" value={candidate.nameEn}/><Info label="연락처" value={candidate.phone}/><Info label="이메일" value={candidate.email}/></dl><Link href={`/candidates/${candidate.id}`} className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-blue-800">후보자 전체 Job 보기 <ExternalLink className="h-4 w-4"/></Link></Section><Section title="Job 기본정보"><dl className="grid gap-5 sm:grid-cols-2"><Info label="Job No." value={job.jobNo}/><Info label="인증규격" value={job.standard}/><Info label="현재등급" value={job.currentGrade}/><Info label="누적 처리 회차" value={`${cycles.length}회`}/></dl><div className="mt-5 rounded-md bg-slate-50 p-3 text-xs leading-5 text-slate-600">Job No.는 규격별로 유지되며 갱신·등급변경은 새 처리 회차로 누적됩니다.</div></Section></div>}
    {active==="현재 처리"&&(current?<div className="space-y-5">{notice&&<div role="status" className="rounded-md border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-medium text-blue-900">{notice}</div>}<section className="rounded-lg border bg-slate-900 p-5 text-white"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-slate-300">현재 처리 회차</p><p className="mt-1 text-xl font-semibold">{current.sequence}회차 · {current.applicationType}</p><p className="mt-1 text-sm text-slate-300">신청일 {current.applicationDate}</p></div><StatusBadge status={activeStatus??current.status}/></div></section><Section title="자동 계산 업무일자" description={`인증발행일 기준 · ${current.appliedRule}`}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DateCard label="서류검토일" value={current.documentReviewDate}/><DateCard label="인증심의일" value={current.decisionDate}/><DateCard label="인증발행일" value={current.plannedIssueDate} locked/><DateCard label="문서전달일" value={current.deliveryDate}/></div></Section>{activeStatus==="SUPPLEMENT_PENDING"?<Section title="보완 대기" description="보완자료 접수 후 서류 재검토를 시작합니다."><div className="rounded-md border border-orange-200 bg-orange-50 p-4"><div className="flex items-center gap-2 font-semibold text-orange-900"><AlertTriangle className="h-5 w-5"/>교육 증빙 보완 필요</div><p className="mt-2 text-sm text-orange-800">요청일 2026-08-29 · 요청자 오실무 · 1차 서류검토</p><p className="mt-2 text-sm text-slate-600">교육 이수시간을 확인할 수 있는 증빙자료를 추가 제출해 주세요.</p></div><div className="mt-5 flex justify-end"><Button className="bg-blue-800 hover:bg-blue-900" onClick={()=>{setActiveStatus("DOCUMENT_REVIEW");setNotice("보완자료 접수를 기록하고 서류 재검토 단계로 전환했습니다.");}}>보완자료 접수 및 재검토 시작</Button></div></Section>:<ReviewForm onNotice={setNotice} onComplete={()=>setActiveStatus("INVOICE_PENDING")}/>}</div>:<Section title="진행 중인 처리 회차 없음" description="기존 회차가 모두 완료되었습니다."><Button asChild className="bg-blue-800 hover:bg-blue-900"><Link href={`/cycles/new?job=${job.id}`}>새 처리 회차 등록</Link></Button></Section>)}
    {active==="회차 이력"&&<Section title="처리 회차 이력" description="완료된 회차는 수정되지 않고 시간순으로 누적됩니다."><div className="space-y-3">{cycles.map((cycle)=><div key={cycle.id} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center"><div className={`grid h-10 w-10 place-items-center rounded-full ${cycle.status==="COMPLETED"?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{cycle.sequence}</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{cycle.sequence}회차 · {cycle.applicationType}</p><StatusBadge status={cycle.status}/></div><p className="mt-1 text-sm text-slate-500">신청 {cycle.applicationDate} · 인증발행 {cycle.plannedIssueDate}</p></div><p className="text-xs text-slate-400">{cycle.appliedRule}</p></div>)}</div></Section>}
    {active==="인증정보"&&<Section title="인증정보 이력" description="현재 인증과 과거 발행정보를 Job에 연결해 추적합니다."><div className="grid gap-5 sm:grid-cols-2"><Info label="인증번호" value={job.certificationNo??"미발행"}/><Info label="인증상태" value={certificationStateLabels[job.certificationState]}/><Info label="최근 인증발행일" value={cycles.find(c=>c.status==="COMPLETED")?.plannedIssueDate??current?.plannedIssueDate??"-"}/><Info label="현재등급" value={job.currentGrade}/></div><div className="mt-5 rounded-md border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">인증서 자동발행은 현재 범위에 포함되지 않습니다.</div></Section>}
    {active==="정지·철회"&&<Section title="인증 사후관리" description="정지·철회는 표준 사유와 상세 사유를 별도 기록합니다."><div className="grid gap-5 sm:grid-cols-2"><Field label="처리구분"><select className={controlClass}><option>인증 정지</option><option>인증 철회</option></select></Field><Field label="대상 인증번호"><input className={controlClass} value={job.certificationNo??"미발행"} readOnly/></Field><Field label="표준 사유"><select className={controlClass}><option>자격유지 요구사항 미충족</option><option>인증서 오용</option><option>시정조치 미이행</option><option>기타</option></select></Field><Field label="효력 발생일"><input type="date" className={controlClass}/></Field><Field label="상세 사유" className="sm:col-span-2"><textarea className={textareaClass} placeholder="보고서에 반영할 상세 사유를 입력합니다."/></Field></div>{notice&&<p role="status" className="mt-4 rounded-md bg-blue-50 px-4 py-3 text-sm text-blue-900">{notice}</p>}<div className="mt-5 flex justify-end"><Button variant="outline" onClick={()=>setNotice("정지·철회 보고서 미리보기 데이터를 준비했습니다. 실제 Word 양식 연결은 다음 문서 자동화 단계에서 적용합니다.")}><FileText/>보고서 미리보기</Button></div></Section>}
    {active==="처리이력"&&<Section title="처리이력" description="업무일자와 별도로 시스템 감사시각을 기록합니다."><ol className="relative ml-2 border-l border-slate-200">{auditLogs.filter((log)=>log.jobId===job.id).map((log)=><li key={log.id} className="relative ml-6 pb-7 last:pb-0"><span className="absolute -left-[31px] top-1 grid h-4 w-4 place-items-center rounded-full bg-blue-800 ring-4 ring-white"><Circle className="h-2 w-2 fill-white text-white"/></span><p className="text-xs text-slate-500">{log.occurredAt}</p><div className="mt-1 flex flex-wrap items-baseline gap-2"><p className="font-semibold">{log.action}</p><span className="text-sm text-slate-500">{log.actor}</span></div>{log.detail&&<p className="mt-1 text-sm text-blue-800">{log.detail}</p>}</li>)}</ol></Section>}
  </div>
}
function Section({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="rounded-lg border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-semibold">{title}</h3>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div><div className="p-5">{children}</div></section>}
function Summary({label,value}:{label:string;value:string}){return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1.5 text-sm font-semibold text-slate-900">{value}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1.5 text-sm font-medium text-slate-900">{value}</dd></div>}
function DateCard({label,value,locked}:{label:string;value:string;locked?:boolean}){return <div className={`rounded-md border p-4 ${locked?"border-blue-200 bg-blue-50":"bg-slate-50"}`}><div className="flex items-center gap-2 text-xs font-medium text-slate-500">{locked?<LockKeyhole className="h-3.5 w-3.5"/>:<CalendarDays className="h-3.5 w-3.5"/>}{label}</div><p className="mt-2 font-semibold text-slate-900">{value}</p>{locked&&<p className="mt-1 text-[11px] text-blue-700">기준일 · 수정 불가</p>}</div>}
function ReviewForm({onNotice,onComplete}:{onNotice:(message:string)=>void;onComplete:()=>void}){return <Section title="서류검토" description="외부 문서는 내부 링크로 참조하고 확인 결과만 기록합니다."><div className="grid gap-3 sm:grid-cols-2">{documents.map((doc,index)=><label key={doc} className="flex items-center gap-3 rounded-md border p-3 text-sm"><Checkbox defaultChecked={index<3}/>{doc}<button type="button" onClick={()=>onNotice(`${doc}의 외부 보관 경로는 Dropbox 연결 후 열 수 있습니다.`)} className="ml-auto inline-flex items-center gap-1 text-xs text-blue-700">문서 링크 <ExternalLink className="h-3 w-3"/></button></label>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="검토자"><input className={controlClass} defaultValue="김담당"/></Field><Field label="양식 기재일"><input type="date" className={controlClass} defaultValue="2026-09-04"/></Field><Field label="검토의견" className="sm:col-span-2"><textarea className={textareaClass} placeholder="검토의견을 입력합니다."/></Field></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>onNotice("서류검토 내용을 이 브라우저에 임시저장했습니다.")}><Save/>임시저장</Button><Button className="bg-blue-800 hover:bg-blue-900" onClick={()=>{onComplete();onNotice("서류검토를 완료하고 인보이스 발행 대기 단계로 전환했습니다.");}}><Check/>서류검토 완료</Button></div></Section>}
