"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {hasEnvVars} from "@/lib/utils";
import {cleanStaffTestReport,isStaffTestReport,mergeStaffTestReports,newStaffTestReport,staffTestCases,staffTestReportIssues,staffTestStorageKey,summarizeStaffTests,testStatuses,type StaffTestReport,type StaffTestStatus} from "@/lib/staff-test-checklist";
import {shouldConfirmLink} from "@/lib/unsaved-change-policy";

type Stored={report:StaffTestReport;collected:StaffTestReport[]};
function isStored(value:unknown):value is Stored{if(!value||typeof value!=="object")return false;const row=value as Stored;return isStaffTestReport(row.report)&&Array.isArray(row.collected)&&row.collected.length<=200&&row.collected.every(isStaffTestReport);}
export function StaffTestChecklist(){
 const [report,setReport]=useState<StaffTestReport|null>(null),[collected,setCollected]=useState<StaffTestReport[]>([]),[filter,setFilter]=useState("전체"),[group,setGroup]=useState("전체"),[notice,setNotice]=useState(""),[blocked,setBlocked]=useState(false),[saved,setSaved]=useState("");
 const rawRef=useRef<string|null>(null),importBusy=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{
  try{const raw=window.localStorage.getItem(staffTestStorageKey);rawRef.current=raw;if(raw){const parsed:unknown=JSON.parse(raw);if(!isStored(parsed))throw Error("손상된 점검표");const clean={report:cleanStaffTestReport(parsed.report),collected:parsed.collected.map(cleanStaffTestReport)};setReport(clean.report);setCollected(clean.collected);setSaved(JSON.stringify(clean));}else setReport(newStaffTestReport(crypto.randomUUID(),hasEnvVars?"SHARED":"LOCAL",new Date().toISOString()));}
  catch{setBlocked(true);setNotice("점검표 저장값을 읽지 못했습니다. 기존 기록을 덮어쓰지 않습니다. 다른 브라우저에서 테스트하거나 관리자에게 문의해 주세요.");}
 },[]);
 const current=report?JSON.stringify({report,collected}):"";
 const dirty=Boolean(report&&current!==saved);
 useEffect(()=>{if(!dirty)return;const handler=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};const click=(event:MouseEvent)=>{const link=event.target instanceof Element?event.target.closest("a[href]"):null;if(!(link instanceof HTMLAnchorElement)||!shouldConfirmLink({dirty,href:link.href,currentHref:window.location.href,target:link.target,download:link.hasAttribute("download"),modified:event.ctrlKey||event.metaKey||event.shiftKey||event.altKey||event.button!==0}))return;if(!window.confirm("점검 결과에 저장하지 않은 변경이 있습니다. 저장하지 않고 이동할까요?")){event.preventDefault();event.stopPropagation();}};window.addEventListener("beforeunload",handler);document.addEventListener("click",click,true);return()=>{window.removeEventListener("beforeunload",handler);document.removeEventListener("click",click,true);};},[dirty]);
 const patch=(id:string,status:StaffTestStatus,note?:string)=>setReport(previous=>previous?{...previous,updatedAt:new Date().toISOString(),results:previous.results.map(item=>item.id===id?{...item,status,note:note??item.note}:item)}:previous);
 const save=()=>{
  if(!report||blocked)return;
  const issues=staffTestReportIssues(report);if(issues.length){setNotice(issues.join(" / "));return;}
  try{if(window.localStorage.getItem(staffTestStorageKey)!==rawRef.current){setNotice("다른 탭에서 점검표가 변경되었습니다. 덮어쓰지 않았습니다. 현재 결과를 내보낸 뒤 다시 열어 주세요.");return;}window.localStorage.setItem(staffTestStorageKey,current);rawRef.current=current;setSaved(current);setNotice("이 브라우저에 저장했습니다. 다른 직원과 자동 공유되지는 않습니다.");}
  catch{setNotice("저장하지 못했습니다. 브라우저 저장 공간/권한을 확인하고 결과를 내보내 주세요.");}
 };
 const download=()=>{
  if(!report||blocked)return;const issues=staffTestReportIssues(report);if(issues.length){setNotice(issues.join(" / "));return;}
  if(!window.confirm("이름·메모에 실제 고객 개인정보나 비밀번호가 없는지 확인해 주세요. 현재 점검 결과를 JSON 파일로 내보낼까요?"))return;
  try{const blob=new Blob([JSON.stringify(cleanStaffTestReport(report),null,2)],{type:"application/json;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`업무테스트-${report.runId.slice(0,8)}.json`;document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("파일 다운로드를 요청했습니다. 실제 파일 저장 여부를 확인한 후 관리자에게 전달해 주세요.");}catch{setNotice("내보내기에 실패했습니다. 다시 시도해 주세요.");}
 };
 const collect=async(files:FileList|null)=>{
  if(!files?.length||blocked||importBusy.current)return;
  importBusy.current=true;
  try{if(files.length>50)throw Error("한 번에 최대 50개 파일을 선택해 주세요.");const incoming:StaffTestReport[]=[];for(const file of Array.from(files)){if(file.size>100000)throw Error("100KB 이하의 점검표 파일만 사용할 수 있습니다.");const value:unknown=JSON.parse(await file.text());if(!isStaffTestReport(value)||staffTestReportIssues(value).length)throw Error("지원하지 않거나 항목이 누락된 점검표입니다. 입력 전체를 반영하지 않았습니다.");incoming.push(cleanStaffTestReport(value));}if(!mounted.current)return;setCollected(previous=>{const merged=mergeStaffTestReports(previous,incoming);if(merged.length>200){setNotice("최대 200개 점검표를 모을 수 있습니다. 이번 가져오기는 반영하지 않았습니다.");return previous;}return merged;});setNotice("점검표를 가져왔습니다. 이 브라우저 저장 버튼을 눌러 보관해 주세요. 동일 점검표는 더 최신 결과만 반영합니다.");}
  catch(error){if(mounted.current)setNotice(error instanceof Error?error.message:"점검표를 가져오지 못했습니다.");}finally{importBusy.current=false;}
 };
 const totals=summarizeStaffTests(report?[report]:[]),shared=summarizeStaffTests(collected);
 return <div className="space-y-5"><section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">샘플 데이터로 업무 흐름 점검</h2><p className="mt-2 text-sm text-muted-foreground">이 점검표는 수동 테스트 기록입니다. 통과 표시는 자동검증·운영 승인과 다릅니다. 실제 고객 이름·연락처·이메일·비밀번호는 입력하지 말고 샘플 번호와 재현 절차만 작성해 주세요.</p><p className="mt-2 text-sm font-medium">각 직원의 브라우저에만 저장됩니다. 결과 내보내기 → 관리자에게 전달 → 관리자 화면에서 가져오기 순서로 모아봅니다.</p><p className="mt-3 text-sm" role="status">{blocked?"기존 기록 보호 중":!report?"불러오는 중":dirty?"미저장 변경 있음":"이 브라우저 저장 완료"}</p><div className="mt-4 flex flex-wrap gap-3"><label className="text-sm">테스트 담당자 별칭<input className="ml-2 rounded-md border bg-background p-2" maxLength={80} value={report?.reviewer??""} disabled={!report||blocked} onChange={event=>setReport(previous=>previous?{...previous,reviewer:event.target.value,updatedAt:new Date().toISOString()}:previous)}/></label><Button disabled={!report||blocked} onClick={save}>이 브라우저에 저장</Button><Button variant="outline" disabled={!report||blocked} onClick={download}>내 결과 내보내기(JSON)</Button></div><p className="mt-3 text-xs text-muted-foreground">테스트 환경: {report?.environment==="SHARED"?"공유 서버 설정 환경":"로컬 샘플 환경"} · 이 표시는 실제 DB 저장이나 권한 검증을 보장하지 않습니다.</p></section>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(testStatuses).map(([key,label])=><div key={key} className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{totals[key as StaffTestStatus]}건</p></div>)}</div>
 <div className="flex flex-wrap gap-3"><label className="text-sm">업무 범주<select className="ml-2 rounded-md border bg-background p-2" value={group} onChange={event=>setGroup(event.target.value)}>{["전체",...new Set(staffTestCases.map(item=>item.group))].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm">점검 결과<select className="ml-2 rounded-md border bg-background p-2" value={filter} onChange={event=>setFilter(event.target.value)}><option>전체</option>{Object.entries(testStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
 <div className="space-y-3">{staffTestCases.filter(test=>(group==="전체"||test.group===group)&&(filter==="전체"||report?.results.find(item=>item.id===test.id)?.status===filter)).map(test=>{const result=report?.results.find(item=>item.id===test.id);return <section key={test.id} className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{test.group}</p><h3 className="mt-1 font-semibold">{test.title}</h3></div><Link className="text-sm underline" href={test.href} target="_blank" rel="noopener noreferrer">해당 업무 새 탭 열기</Link></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{test.steps}</p><label className="mt-3 block text-sm">결과<select className="ml-2 rounded-md border bg-background p-2" disabled={!result||blocked} value={result?.status??"NOT_RUN"} onChange={event=>patch(test.id,event.target.value as StaffTestStatus)}>{Object.entries(testStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="mt-3 block text-sm">재현 절차·기대 결과·실제 결과 {result?.status==="FAIL"||result?.status==="BLOCKED"?"(필수)":"(선택)"}<textarea className="mt-2 min-h-20 w-full rounded-md border bg-background p-3" disabled={!result||blocked} maxLength={1500} value={result?.note??""} placeholder="예: 샘플 T-01 / 1차 검토 저장 → 새로고침 / 기대: 적합 유지 / 실제: 미입력으로 표시" onChange={event=>result&&patch(test.id,result.status,event.target.value)}/></label></section>;})}</div>
 <section className="rounded-xl border bg-card p-5"><h3 className="font-semibold">직원 점검 결과 모아보기</h3><p className="mt-2 text-sm text-muted-foreground">직원이 전달한 JSON 점검표를 선택하세요. 공유 DB로 업로드하지 않으며 이 브라우저에 저장해야 다음에도 확인할 수 있습니다.</p><input className="mt-3 block text-sm" type="file" accept="application/json,.json" multiple disabled={!report||blocked} aria-label="직원 점검 결과 가져오기" onChange={event=>{void collect(event.target.files);event.target.value="";}}/><p className="mt-3 text-sm">점검표 {collected.length}개 · 통과 {shared.PASS}건 · 문제 발견 {shared.FAIL}건 · 진행 불가 {shared.BLOCKED}건 · 미실행 {shared.NOT_RUN}건</p><div className="mt-4 space-y-3">{collected.map(item=><div key={item.runId} className="rounded-md border p-3"><p className="text-sm font-medium">{item.reviewer||"별칭 미입력"} · {item.runId.slice(0,8)} · {new Date(item.updatedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}</p>{item.results.filter(result=>result.status==="FAIL"||result.status==="BLOCKED").map(result=><div key={result.id} className="mt-2 text-sm"><p className="font-medium">{testCasesTitle(result.id)} · {testStatuses[result.status]}</p><p className="whitespace-pre-wrap text-muted-foreground">{result.note}</p></div>)}{!item.results.some(result=>result.status==="FAIL"||result.status==="BLOCKED")&&<p className="mt-2 text-xs text-muted-foreground">기록된 문제 발견·진행 불가 항목이 없습니다. 전체 통과를 의미하지는 않습니다.</p>}</div>)}</div></section>
 {notice&&<p className="rounded-md border bg-card p-4 text-sm" role="status">{notice}</p>}<div className="flex justify-end"><Button disabled={!report||blocked} onClick={save}>점검 결과 저장</Button></div></div>;
}
function testCasesTitle(id:string){return staffTestCases.find(item=>item.id===id)?.title??id;}
