import { reportApplicationTypeLabel, reportGroupLabel, reportStateLabel } from "@/lib/report-export";

export type MonthlyPrintGroup = { area: string; standard: string; received: number; issued: number; active: number; suspended: number; withdrawn: number };
export type MonthlyPrintDetail = { candidateName: string; partner: string; jobNo: string; standard: string; grade: string; applicationType: string; certificationNo: string; certificationState: string; receivedAt: string; issueDate: string };
export function buildMonthlyReportPrintHtml(input: {
  month: string; metadata: string[][]; summary: { total: number; issued: number; active: number; suspended: number; withdrawn: number };
  groups: MonthlyPrintGroup[]; details?: MonthlyPrintDetail[];
}) {
  const escape = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
  const cells = (values: unknown[]) => values.map((value) => `<td>${escape(value)}</td>`).join("");
  const table = (headings: string[], rows: unknown[][]) => `<table><thead><tr>${headings.map((heading) => `<th scope="col">${escape(heading)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${cells(row)}</tr>`).join("")}</tbody></table>`;
  const groups = table(["분야", "표준·세부 분야", "대상 Job", "인증발행", "유지", "정지", "철회"], input.groups.map((row) => [reportGroupLabel(row.area, "businessArea"), row.standard, row.received, row.issued, row.active, row.suspended, row.withdrawn]));
  const details = input.details?.length ? `<section class="details"><h2>대상 상세 (고객정보 포함)</h2>${table(["후보자", "파트너사", "Job No.", "표준", "등급", "신청 유형", "인증번호", "현재 상태", "접수일", "발행일"], input.details.map((row) => [row.candidateName, row.partner, row.jobNo, row.standard, row.grade, reportApplicationTypeLabel(row.applicationType), row.certificationNo, reportStateLabel(row.certificationState), row.receivedAt, row.issueDate]))}</section>` : "";
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${escape(input.month)} 월간 업무보고</title><style>
  @page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{font-family:"Malgun Gothic",sans-serif;color:#172033;font-size:11px}h1{font-size:21px;margin:0 0 12px}h2{font-size:15px;margin-top:20px}.metadata{display:grid;grid-template-columns:1fr 1fr;gap:4px 14px;padding:12px;border:1px solid #aaa}.metadata p{margin:0;overflow-wrap:anywhere}.cards{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.card{border:1px solid #aaa;padding:10px;min-width:110px}.card b{font-size:18px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:10px}th,td{border:1px solid #777;padding:6px;text-align:left;overflow-wrap:anywhere;white-space:pre-wrap}th{background:#eee}thead{display:table-header-group}tr{break-inside:avoid}.details{break-before:page}.notice{margin:12px 0;font-size:10px;color:#555}.internal{border-top:1px solid #aaa;padding-top:8px;margin-top:16px}
  </style></head><body><h1>${escape(input.month)} 월간 업무보고</h1><div class="metadata">${input.metadata.map(([key, value]) => `<p><strong>${escape(key)}</strong>: ${escape(value)}</p>`).join("")}</div><p class="notice">현재 인증상태 기준입니다. 과거 월말 상태를 의미하지 않습니다. 이 출력은 브라우저 인쇄용이며 공식 패키지 PDF가 아닙니다.</p><div class="cards">${[["대상 Job", input.summary.total], ["인증발행", input.summary.issued], ["유지", input.summary.active], ["정지", input.summary.suspended], ["철회", input.summary.withdrawn]].map(([label, count]) => `<div class="card">${escape(label)}<br><b>${escape(count)}</b>건</div>`).join("")}</div><h2>표준별 집계</h2>${groups}${details}<p class="internal">내부 업무용 · 권한 없는 사람에게 공유하지 마세요. 출력물 및 내려받은 파일은 별도로 안전하게 보관해야 합니다.</p><script>window.onload=()=>window.print();</script></body></html>`;
}
