import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, Mail, MapPin, Pencil, Phone, Plus } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { certificationStateLabels, candidates, getCandidate, getCurrentCycle, jobs } from "@/data/mock-data";
export function generateStaticParams(){return candidates.map((candidate)=>({id:candidate.id}));}
export default async function CandidatePage({params}:{params:Promise<{id:string}>}){const {id}=await params;const candidate=getCandidate(id);if(!candidate)notFound();const ownedJobs=jobs.filter((job)=>job.candidateId===id);return <AppShell title={candidate.name} description={`${candidate.nameEn} · 후보자 상세`} actions={<div className="flex gap-2"><Button variant="outline"><Pencil/>기본정보 수정</Button><Button className="bg-blue-800 hover:bg-blue-900"><Plus/>새 Job 등록</Button></div>}><Link href="/candidates" className="mb-4 inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-900"><ArrowLeft className="h-4 w-4"/>후보자 목록</Link><section className="rounded-lg border bg-white p-6 shadow-sm"><div className="grid gap-6 md:grid-cols-[180px_1fr]"><div className="grid h-28 w-28 place-items-center rounded-full bg-slate-100 text-3xl font-semibold text-slate-500">{candidate.name.slice(0,1)}</div><dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2 xl:grid-cols-3"><Info label="생년월일" value={candidate.birthDate}/><Info label="국적" value={candidate.nationality}/><Info label="연락처" value={candidate.phone} icon={<Phone/>}/><Info label="이메일" value={candidate.email} icon={<Mail/>}/><Info label="주소" value={candidate.address} icon={<MapPin/>} wide/></dl></div></section><section className="mt-6 overflow-hidden rounded-lg border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">보유 Job</h2><p className="mt-1 text-sm text-slate-500">인증규격별 Job과 현재 인증상태입니다.</p></div><span className="text-sm font-medium text-slate-500">{ownedJobs.length}건</span></div><div className="divide-y">{ownedJobs.map((job)=>{const cycle=getCurrentCycle(job);return <Link key={job.id} href={`/jobs/${job.id}`} className="flex flex-col gap-3 p-5 hover:bg-slate-50 sm:flex-row sm:items-center"><span className="grid h-10 w-10 place-items-center rounded-md bg-blue-50 text-blue-800"><BriefcaseBusiness className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-blue-800">{job.jobNo}</p><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${job.certificationState==="ACTIVE"?"bg-emerald-50 text-emerald-800":job.certificationState==="SUSPENDED"?"bg-orange-50 text-orange-800":"bg-slate-100 text-slate-600"}`}>{certificationStateLabels[job.certificationState]}</span></div><p className="mt-1 text-sm text-slate-600">{job.standard} · {job.currentGrade}</p></div><div className="text-sm text-slate-500 sm:text-right"><p>{cycle?`${cycle.sequence}회차 ${cycle.applicationType} 진행 중`:"진행 회차 없음"}</p><p className="mt-1 text-xs">주 담당자 {job.primaryOwner}</p></div></Link>})}</div></section></AppShell>}
function Info({label,value,icon,wide}:{label:string;value:string;icon?:React.ReactNode;wide?:boolean}){return <div className={wide?"sm:col-span-2 xl:col-span-3":""}><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1.5 flex items-center gap-2 text-sm font-medium text-slate-900">{icon&&<span className="text-slate-400 [&_svg]:h-4 [&_svg]:w-4">{icon}</span>}{value}</dd></div>}
