import Link from "next/link";
import { Suspense } from "react";
import { ArrowLeft, CalendarDays, Save } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Field, controlClass } from "@/components/form-fields";
import { Button } from "@/components/ui/button";
import { getCandidate, getJob, jobs } from "@/data/mock-data";
export default function NewCyclePage({searchParams}:{searchParams:Promise<{job?:string}>}){return <AppShell title="새 처리 회차" description="완료된 Job에 갱신 또는 변경 업무를 시작합니다."><Suspense fallback={<div className="rounded-lg border bg-white p-8 text-sm text-slate-500">대상 Job을 불러오는 중입니다.</div>}><NewCycleContent searchParams={searchParams}/></Suspense></AppShell>}
async function NewCycleContent({searchParams}:{searchParams:Promise<{job?:string}>}){const {job:jobId}=await searchParams;const job=getJob(jobId??"")??jobs[3];const candidate=getCandidate(job.candidateId)!;return <div className="max-w-4xl"><Link href={`/jobs/${job.id}`} className="mb-4 inline-flex items-center gap-1 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/>{job.jobNo}로 돌아가기</Link><section className="mb-5 rounded-lg border bg-slate-900 p-5 text-white"><p className="text-xs font-medium text-slate-300">대상 Job</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xl font-semibold">{job.jobNo}</p><p className="mt-1 text-sm text-slate-300">{candidate.name} · {job.standard} · {job.currentGrade}</p></div><p className="text-sm text-slate-300">기존 완료 회차 {job.cycleIds.length}건</p></div></section><form className="rounded-lg border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="font-semibold">회차 기본정보</h2><p className="mt-1 text-sm text-slate-500">Job No.는 유지되며 새로운 처리 회차만 추가됩니다.</p></div><div className="grid gap-5 p-6 sm:grid-cols-2"><Field label="신청구분" required><select className={controlClass} defaultValue="갱신"><option>갱신</option><option>등급변경</option><option>범위확대</option><option>기타</option></select></Field><Field label="신청일" required><input type="date" className={controlClass} defaultValue="2026-08-30"/></Field><Field label="변경 후 등급"><input className={controlClass} defaultValue={job.currentGrade}/></Field><Field label="인증발행일" required><input type="date" className={controlClass} defaultValue="2026-09-25"/></Field><div className="sm:col-span-2 rounded-lg border border-blue-100 bg-blue-50 p-5"><div className="flex items-center gap-2 text-blue-900"><CalendarDays className="h-5 w-5"/><p className="font-semibold">영업일 기준 자동 계산</p></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><DateInfo label="서류검토일" value="2026-09-11"/><DateInfo label="인증심의일" value="2026-09-18"/><DateInfo label="문서전달일" value="2026-09-30"/></div><p className="mt-3 text-xs text-blue-700">업무일자 규칙 v1 · 대한민국 공휴일과 주말 제외</p></div></div><div className="flex justify-end gap-2 border-t bg-slate-50 px-6 py-4"><Button variant="outline" asChild><Link href={`/jobs/${job.id}`}>취소</Link></Button><Button type="button" className="bg-blue-800 hover:bg-blue-900"><Save/>처리 회차 등록</Button></div></form></div>}
function DateInfo({label,value}:{label:string;value:string}){return <div className="rounded-md bg-white p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold text-slate-900">{value}</p></div>}
